#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# AppRun — entry point for the TuxPanel Installer AppImage.

HERE="$(dirname "$(readlink -f "$0")")"
export PYTHONPATH="${HERE}/usr/lib/python3/dist-packages:${HERE}/opt/python/lib/python3.10/site-packages:${PYTHONPATH:-}"
export PATH="${HERE}/opt/python/bin:${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH:-}"
exec "${HERE}/opt/python/bin/python3" -m tuxpanel_installer "$@"
