#!/bin/bash
# SPDX-License-Identifier: GPL-3.0-or-later
# AppRun — entry point for the TuxPanel Installer AppImage.

HERE="$(dirname "$(readlink -f "$0")")"
export PYTHONPATH="${HERE}/usr/lib/python3/dist-packages:${PYTHONPATH}"
export PATH="${HERE}/usr/bin:${PATH}"
exec python3 -m tuxpanel_installer "$@"
