#!/usr/bin/env bash
# ============================================================
#  TuxPanel — Sudoers Setup for the Node Service Account
#
#  This creates a fine-grained sudoers drop-in so the 'tuxpanel'
#  (or current) user can run ONLY the specific binaries needed,
#  with NOPASSWD.  No blanket root access.
#
#  Run as root:  sudo bash scripts/setup-sudoers.sh [username]
# ============================================================

set -euo pipefail

TARGET_USER="${1:-$(logname 2>/dev/null || echo $SUDO_USER)}"
SUDOERS_FILE="/etc/sudoers.d/tuxpanel"

if [[ $EUID -ne 0 ]]; then
  echo "ERROR: Run this script with sudo." >&2
  exit 1
fi

echo "Setting up sudoers for user: ${TARGET_USER}"

cat > "$SUDOERS_FILE" <<EOF
# TuxPanel — least-privilege sudo rules
# Generated by scripts/setup-sudoers.sh

# Samba management
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/smbstatus
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/smbcontrol
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/pdbedit
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/testparm

# User & group management
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/useradd
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/usermod
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/userdel
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/groupadd
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/groupmod
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/groupdel

# Systemd service control (limited to specific units)
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl start smb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl stop smb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart smb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl start nmb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl stop nmb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart nmb
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl start nfs-server
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl stop nfs-server
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl restart nfs-server

# NFS exports
${TARGET_USER} ALL=(root) NOPASSWD: /usr/sbin/exportfs

# Firewall
${TARGET_USER} ALL=(root) NOPASSWD: /usr/bin/firewall-cmd
EOF

chmod 0440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE"

echo "✓ Sudoers rules written to ${SUDOERS_FILE}"
